### ISSUE TITLE
Skybox Rendering Not Working on Real Phone

### ISSUE THREAD

**Issue by AdrienBousquieEPFL** [LookUpGroup27/LookUp#211]
## Description
The Skybox feature in the app is not working on real devices. Through regression testing, it has been identified that the issue is linked to the Skybox code. 

Additionally, the following error appears in Logcat on the emulator, which might be related to the issue. This needs verification on a physical device to confirm if it is the root cause of the problem.

### Logcat Error
```
emuglGLESv2_enc         com.github.lookupgroup27.lookup      E  device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glVertexAttribPointer:738 GL error 0x501 condition [indx >= CODEC_MAX_VERTEX_ATTRIBUTES]
```

## Expected Behavior
The Skybox should render correctly on both emulators and real devices without any errors.

## Steps to Reproduce
1. Run the app on a real device.
2. Navigate to the map.
3. Observe the nothing renders.

## Current Behavior
- The Skybox does not work on real devices.
- Logcat displays errors on the emulator.

## Tasks
- [ ] Verify if the Logcat error appears on a real device.
- [ ] Investigate the cause of the Logcat error.
- [ ] Update this issue with additional findings.
- [ ] Implement a fix for the issue.

## Additional Notes
This issue should be prioritized and updated as more information becomes available.

**Comment by AdrienBousquieEPFL** [comment]
Based on the assumption that most of our users will have the capability to render 2048x2048 images, we have decided not to support multi-device textures at this time. By standardizing on the 2048 format, we can focus our resources on addressing higher-priority issues and improving overall efficiency.
