### ISSUE TITLE
Add Button to Reset FOV and Zoom Controls

### ISSUE THREAD

**Issue by AdrienBousquieEPFL** [LookUpGroup27/LookUp#219]
## Description

Enhance the zoom functionality by adding:

1. **Reset FOV Button**: A button to reset the zoom (FOV) to its default value. This would provide a quick way for users to revert to the original zoom level and improve the overall user experience.
2. **Zoom Level Display**: Display the current zoom level, allowing users to see the exact FOV or zoom percentage.
3. **Zoom Adjustment Controls**: Introduce a button or slider to adjust the zoom level up or down so we don't rely only on the existing gesture-based implementation.

### Expected Behavior
- **Reset FOV Button**:
  - Clicking this button resets the FOV to the default value.
  - Example implementation for resetting in `Camera` class:
    
    ```kotlin
    fun resetFOV() {
        fov = DEFAULT_FOV
        Matrix.perspectiveM(projMatrix, 0, fov, aspectRatio, NEAR, FAR)
    }
    ```

- **Zoom Level Display**:
  - Shows the current zoom level as a numerical value or percentage or multiplication value (e.g 0.5x, 1x, 2x, ...).
  - The display updates dynamically as the zoom level changes.

- **Zoom Adjustment Controls**:
  - A slider or buttons to increment or decrement the zoom level.
  - The adjustments should feel smooth and provide immediate visual feedback.

### Additional Notes
- The design and behavior of the reset button, zoom level display, and adjustment controls should be clearly defined in the Figma design system.
- The reset functionality could integrate with the existing perspective matrix to ensure compatibility.
- Ensure the new UI elements (button, slider) are non-intrusive and fit seamlessly into the current interface design.

### Task List
- [x] Define the design and behavior of the reset button, zoom level display, and adjustment controls in the Figma design system.
- [x] Implement a functional reset button that restores the FOV to its default value.
- [x] Display the current zoom level as a numerical value or percentage.
- [x] Add controls (button or slider) to adjust the zoom level up and down.
- [ ] Ensure thorough testing to confirm compatibility with existing gesture-based zoom functionality.
